using Newtonsoft.Json;

namespace CluedIn.Crawling.Powerwater.Core.Models
{
    public class GenProd 
    {
        public string Install { get; set; }
        public string Meter { get; set; }
        public string UnbillMeter { get; set; }
        public string PrevMeter { get; set; }
        public string MasInstall { get; set; }
        public string Spare5 { get; set; }
        public string KvaRating { get; set; }
        public string Spare7 { get; set; }
        public string Fcharge { get; set; }
        public string Fcdesc { get; set; }
        public string FchargeMultp { get; set; }
        public string FcstDate { get; set; }
        public string FcenDate { get; set; }
        public string Spare13 { get; set; }
        public string Spare14 { get; set; }
        public string Spare15 { get; set; }
        public string TouenDate { get; set; }
        public string ToustDate { get; set; }
        public string Spare18 { get; set; }
        public string CpIdent { get; set; }
        public string CtNumber { get; set; }
        public string SubStation	 {get; set;}
        public string Shutdown { get; set; }
        public string TouFlag { get; set; }
        public string TouCharge { get; set; }
        public string TouDesc { get; set; }
        public string MrFlag { get; set; }
        public string MrFlagRm { get; set; }
        public string PostEdit { get; set; }
        public string NzedCode { get; set; }
        public string PropNo { get; set; }
        public string Consumer { get; set; }
        public string MrNotes { get; set; }
        public string Pissue { get; set; }
        public string AppCodes { get; set; }
        public string AppQty { get; set; }
        public string AppKw { get; set; }
        public string AppControl { get; set; }
        public string Location { get; set; }
        public string Wissue { get; set; }
        public string SiteNo { get; set; }
        public string RelayNo { get; set; }
        public string AddrFreeform { get; set; }
        public string AddrUnit { get; set; }
        public string AddrHouse { get; set; }
        public string AddrStreet { get; set; }
        public string AddrPoBox	 {get; set;}
        public string AddrSubUrb  { get; set; }
        public string AddrTownCity { get; set; }
        public string AddrPostCode { get; set; }
        public string AddrUnitType { get; set; }
        public string AddrBuilding { get; set; }
        public string AddrState { get; set; }
        public string AddrFloor { get; set; }
        public string AddrCountry { get; set; }
        public string AddrStrType { get; set; }
        public string AddrDirection { get; set; }
        public string AddrCounty { get; set; }
        public string AddrSubdivisn { get; set; }
        public string AddrPostCode2 { get; set; }
        public string Spare43 { get; set; }
        public string BillPer { get; set; }
        public string BillSeq { get; set; }
        public string NextDate { get; set; }
        public string MeterLoc { get; set; }
        public string LastDate { get; set; }
        public string District { get; set; }
        public string PrevNoDays { get; set; }
        public string LreadDate { get; set; }
        public string GasGate { get; set; }
        public string NstType { get; set; }
        public string LbillType { get; set; }
        public string Spare55 { get; set; }
        public string EstSuppress { get; set; }
        public string EstOrideDate { get; set; }
        public string EstOrideType { get; set; }
        public string Spare59 { get; set; }
        public string OwnAcct { get; set; }
        public string LegalPaddrFreeForm { get; set; }
        public string LegalPaddrUnit { get; set; }
        public string LegalPaddrHouse { get; set; }
        public string LegalPaddrStreet { get; set; }
        public string LegalPaddrPoBox     { get; set; }
        public string LegalPaddrSubUrb    { get; set; }
        public string LegalPaddrTownCity { get; set; }
        public string LegalPaddrPostCode { get; set; }
        public string LegalPaddrUnitType { get; set; }
        public string LegalPaddrBuilding { get; set; }
        public string LegalPaddrState { get; set; }
        public string LegalPaddrFloor { get; set; }
        public string LegalPaddrCountry { get; set; }
        public string LegalPaddrStrtype { get; set; }
        public string LegalPaddrDirection { get; set; }
        public string LegalPaddrCounty { get; set; }
        public string LegalPaddrSubdivisn { get; set; }
        public string LegalPaddrPostCode2 { get; set; }
        public string ChgClass { get; set; }
        public string Spare63 { get; set; }
        public string Spare64 { get; set; }
        public string Spare65 { get; set; }
        public string Spare66 { get; set; }
        public string Spare67 { get; set; }
        public string AltEnergyCo { get; set; }
        public string AltEnergyDate { get; set; }
        public string AltEnergyCons { get; set; }
        public string AltLineCo { get; set; }
        public string AltLineDate { get; set; }
        public string MeshBlock { get; set; }
        public string FutureCons { get; set; }
        public string KeyNumber { get; set; }
        public string ConnectDate { get; set; }
        public string DisconnectType { get; set; }
        public string Disconnect { get; set; }
        public string DisconnectReason { get; set; }
        public string ReconnectAuth { get; set; }
        public string ReconnectDate { get; set; }
        public string HvFlag { get; set; }
        public string NominatedKva { get; set; }
        public string MetNetwork { get; set; }
        public string Spare85 { get; set; }
        public string ControlKva { get; set; }
        public string DisconnectLoc { get; set; }
        public string Altitude { get; set; }
        public string LineFactor { get; set; }
        public string NwCostFchg { get; set; }
        public string NwCostFchgMult { get; set; }
        public string AltEnergyEndDate { get; set; }
        public string UtilityType { get; set; }
        public string TieredInx { get; set; }
        public string Spare95 { get; set; }
        public string Spare96 { get; set; }
        public string Spare97 { get; set; }
        public string Spare98 { get; set; }
        public string Spare99 { get; set; }
        public string Spare100 { get; set; }
    }
}
