using Newtonsoft.Json;

namespace CluedIn.Crawling.Powerwater.Core.Models
{
    public class Maximo 
    {
        public string Location { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string ControlAcc { get; set; }
        public string GlAccount { get; set; }
        public string PurchVarAcc { get; set; }
        public string InvoiceVarAcc { get; set; }
        public string CurVarAcc { get; set; }
        public string ShrinkAgeAcc { get; set; }
        public string InvCostAdjAcc { get; set; }
        public string ReceiptVarAcc { get; set; }
        public string ChangeBy { get; set; }
        public string ChangeDate { get; set; }
        public string Disabled { get; set; }
        public string OldControlAcc { get; set; }
        public string OldShrinkAgeAcc { get; set; }
        public string OldInvCostAdjacc { get; set; }
        public string ClassStructureId { get; set; }
        public string GisParam1 { get; set; }
        public string GisParam2 { get; set; }
        public string GisParam3 { get; set; }
        public string SourceSysId { get; set; }
        public string OwnerSysId { get; set; }
        public string ExternalRefId { get; set; }
        public string SenderSysId { get; set; }
        public string SiteId { get; set; }
        public string OrgId { get; set; }
        public string IntLabRec { get; set; }
        public string IsDefault { get; set; }
        public string ShipToAddressCode { get; set; }
        public string ShipToLaborCode { get; set; }
        public string BillToAddressCode { get; set; }
        public string BillToLaborCode { get; set; }
        public string Status { get; set; }
        public string ServiceAddressCode { get; set; }
        public string LocationSid { get; set; }
        public string UseInPopr { get; set; }
        public string ToolControlAcc { get; set; }
        public string LangCode { get; set; }
        public string Hasld { get; set; }
        public string AutoWogen { get; set; }
        public string StatusDate { get; set; }
        public string IsFacility { get; set; }
        public string Facility { get; set; }
        public string Area { get; set; }
        public string Alias { get; set; }
        public string InstalledDate { get; set; }
        public string InstalledBy { get; set; }
        public string Owner { get; set; }
        public string BusinessUnit { get; set; }
        public string Community { get; set; }
        public string Department { get; set; }
        public string Service { get; set; }
        public string PlussFeatureClass { get; set; }
        public string PlussIsGis { get; set; }
        public string RowStamp { get; set; }
        public string PlussAddressCode { get; set; }
        public string PlussDescription { get; set; }
        public string PlussStaddrNumber { get; set; }
        public string PlussStaddrDirPrfx { get; set; }
        public string PlussStaddrStreet { get; set; }
        public string PlussStaddrSttype { get; set; }
        public string PlussStaddrDirSfx { get; set; }
        public string PlussStaddrUnitNum { get; set; }
        public string PlussStreetAddress { get; set; }
        public string PlussAddressLine2 { get; set; }
        public string PlussAddressLine3 { get; set; }
        public string PlussCity { get; set; }
        public string PlussRegionDistrict { get; set; }
        public string PlussCounty { get; set; }
        public string PlussStateProvince { get; set; }
        public string PlussPostalCode { get; set; }
        public string PlussCountry { get; set; }
        public string PlussGeocode { get; set; }
        public string PlussTimezone { get; set; }
        public string PlussLatitude { get; set; }
        public string PlussLongitude { get; set; }
        public string PlussReferencePoint { get; set; }
        public string PlussDirections { get; set; }
        public string IsAutoIssueParts { get; set; }
        public string AutoIssueLeadTime { get; set; }
        public string AutoIssueStatus { get; set; }
        public string IsVehicle { get; set; }
        public string Vendor { get; set; }
        public string PluscDueDate { get; set; }
        public string PluscLoop { get; set; }
        public string PluscPmextDate { get; set; }
        public string IsRecloser { get; set; }
        public string IsFeeder { get; set; }
        public string IsSubStation { get; set; }
        public string FeederId { get; set; }
        public string SubStationId { get; set; }
        public string RecloserId { get; set; }
        public string System { get; set; }
        public string SystemType { get; set; }
        public string Maintainer { get; set; }
        public string ScadaId { get; set; }
        public string FisLegacyId { get; set; }
        public string WimsLegacyId { get; set; }
        public string WfRouteToPerson { get; set; }
        public string WfRouteToPersonGroup { get; set; }
        public string WfInteractive { get; set; }
        public string OldWfRouteToPerson { get; set; }
        public string OldWfRouteToPersonGroup { get; set; }
        public string CommunityEnglishName { get; set; }
        public string CommunityName { get; set; }
        public string CommunityTradition { get; set; }
        public string EntryCondition { get; set; }
        public string Erp { get; set; }
        public string SpecificationDescription { get; set; }
        public string AssetBusinessUnit { get; set; }
        public string AssetDepartment { get; set; }
        public string AssetGroup { get; set; }
        public string AssetOwner { get; set; }
        public string CatchmentMajor { get; set; }
        public string CatchmentMinor { get; set; }
        public string CatchmentZone { get; set; }
        public string CommissionDate { get; set; }
        public string CommunityAcronym { get; set; }
        public string CommunityAlias { get; set; }
        public string CommunityId { get; set; }
        public string CriticalCustomer { get; set; }
        public string DecommissionDate { get; set; }
        public string GisGlobalId { get; set; }
        public string LocArea { get; set; }
        public string LocCommunity { get; set; }
        public string LocRegion { get; set; }
        public string MaintainerBusinessUnit { get; set; }
        public string MaintainerDepartment { get; set; }
        public string MaintainerGroup { get; set; }
        public string PendingEdit { get; set; }
        public string WaterSystem { get; set; }
        public string WfEscalationDays { get; set; }
        public string WfMemoList { get; set; }
        public string WfStatus { get; set; }
        public string LocationCode { get; set; }
        public string FisLegacyTbName { get; set; }
        public string Locality { get; set; }
        public string Rdspp { get; set; }
        public string SubUrb { get; set; }
        public string GisErrorMessage { get; set; }
        public string GisProcessedDate { get; set; }
        public string DogCode { get; set; }
        public string CriticalCode { get; set; }
        public string CriticalFlag { get; set; }
        public string CustomerCode { get; set; }
        public string ConsumerCode { get; set; }
        public string ServiceEnduse { get; set; }
        public string IsThreateningCustomer { get; set; }
        public string DisconnectDate { get; set; }
        public string MeterLocationCode { get; set; }
        public string MeterRemarks { get; set; }
        public string TenantCode { get; set; }
        public string GisServiceName { get; set; }
        public string MultipleAssets { get; set; }
        public string LocClassificationId { get; set; }
        public string ClasssHortCode { get; set; }
        public string IsPvMeter { get; set; }
        public string KeyNumber { get; set; }
        public string MeterPostion { get; set; }
        public string PrePaymentMeter {get; set;}
        public string Restrictorapplied { get; set; }
        public string RetailerCode { get; set; }
        public string UndergroundNetwork { get; set; }
        public string CustomerFeeder { get; set; }
        public string FeederCategory { get; set; }
        public string InstallCount { get; set; }
        public string LengthInMetres { get; set; }
        public string NominalkVaLoad { get; set; }
        public string Voltage { get; set; }
        public string AreaInSquareMetres { get; set; }
        public string GisSubType { get; set; }
        public string PressureZoneId { get; set; }
        public string GisLocTemp { get; set; }
        public string IsTestLocation { get; set; }
        public string DecomStore { get; set; }
        public string GisPreventParentUpdate { get; set; }
        public string ManualFeederId { get; set; }
        public string AerFeeder { get; set; }
        public string LocationSyncId { get; set; }
    }
}
